apiVersion: v1
kind: Service
metadata:
  name: trading
  labels:
    app: trading
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: trading
    tier: app-server
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trading
  labels:
    app: trading
spec:
  selector:
    matchLabels:
      app: trading
      tier: app-server
  strategy:
    type: Recreate
  replicas: 2
  template:
    metadata:
      labels:
        app: trading
        tier: app-server
    spec:
      containers:
        - image: fraserraney/trading-app:latest
          name: trading
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://trading-psql:5432/jrvstrading
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: trading-app
                  key: user
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: trading-app
                  key: password
          ports:
            - containerPort: 8080
              name: trading
